services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
  app:
    extends:
      service: base
    command: make dev-local
    environment:
      DATABASE_URL: ${DATABASE_URL}
      MIGRATIONS_DIR: ${MIGRATIONS_DIR}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: packs
    ports:
      - "5432:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
  unit-tests:
    extends:
      service: base
    command: make test-local
